### ISSUE TITLE
BaseRegisterActivity.getViewIdentifiers() returns null

### ISSUE THREAD

**Issue by sharon2719** [sharon2719/Opensrp-client-covax#17]
`2022-06-27 19:21:50.543 27213-27213/org.smartregister.path E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.path, PID: 27213
    java.lang.RuntimeException: Unable to resume activity {org.smartregister.path/com.example.opensrp_client_covax.activity.ChildRegisterActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3784)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at org.smartregister.configurableviews.helper.ConfigurableViewsHelper.registerViewConfigurations(ConfigurableViewsHelper.java:56)
        at org.smartregister.child.model.BaseChildRegisterModel.registerViewConfigurations(BaseChildRegisterModel.java:41)
        at org.smartregister.child.presenter.BaseChildRegisterPresenter.registerViewConfigurations(BaseChildRegisterPresenter.java:57)
        at org.smartregister.view.activity.BaseRegisterActivity.onResumption(BaseRegisterActivity.java:195)
        at org.smartregister.view.activity.SecuredActivity.onResume(SecuredActivity.java:100)
        at org.smartregister.view.activity.BaseRegisterActivity.onResume(BaseRegisterActivity.java:247)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1412)
        at android.app.Activity.performResume(Activity.java:7292)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)`

**Comment by sharon2719** [comment]
What is the purpose of [ChildMetadata](https://github.com/opensrp/opensrp-client-child/blob/master/opensrp-child/src/main/java/org/smartregister/child/domain/ChildMetadata.java) class?
